/* webchat_assets.c: HTML/CSS/JS string literals for the web chat UI */

const char *login_html =
    "<!DOCTYPE html><html><head><meta charset='utf-8'>"
    "<title>aimee - login</title>"
    "<style>"
    "*{box-sizing:border-box;margin:0;padding:0}"
    "body{font-family:system-ui;background:#111;color:#eee;display:flex;"
    "justify-content:center;align-items:center;min-height:100vh}"
    ".card{background:#1a1a2e;border-radius:12px;padding:32px;width:360px;"
    "border:1px solid #333}"
    "h1{font-size:22px;color:#8cf;margin-bottom:24px;text-align:center}"
    "label{display:block;font-size:13px;color:#888;margin-bottom:4px}"
    "input{width:100%;padding:10px 12px;background:#111;color:#eee;border:1px solid #444;"
    "border-radius:6px;font-size:14px;margin-bottom:16px}"
    "input:focus{outline:none;border-color:#8cf}"
    "button{width:100%;padding:10px;background:#234;color:#8cf;border:1px solid #456;"
    "border-radius:6px;font-size:14px;cursor:pointer}"
    "button:hover{background:#345}"
    ".error{color:#f44;font-size:13px;margin-bottom:12px;text-align:center}"
    "</style></head><body>"
    "<div class='card'>"
    "<h1>aimee</h1>"
    "<div id='err' class='error'></div>"
    "<form method='POST' action='/login'>"
    "<label>Username</label>"
    "<input name='username' type='text' autocomplete='username' autofocus required>"
    "<label>Password</label>"
    "<input name='password' type='password' autocomplete='current-password' required>"
    "<button type='submit'>Sign in</button>"
    "</form></div>"
    "<script>"
    "if(location.search.includes('error=1'))"
    "document.getElementById('err').textContent='Invalid credentials';"
    "</script></body></html>";

const char *chat_html =
    "<!DOCTYPE html><html><head><meta charset='utf-8'>"
    "<title>aimee - chat</title>"
    "<style>"
    "*{box-sizing:border-box;margin:0;padding:0}"
    "body{font-family:system-ui;background:#111;color:#eee;height:100vh;display:flex;"
    "flex-direction:column}"
    "nav{background:#1a1a2e;padding:10px 20px;display:flex;align-items:center;gap:16px;"
    "border-bottom:1px solid #333}"
    "nav a{color:#8cf;text-decoration:none;font-size:14px}"
    "nav a:hover{text-decoration:underline}"
    "nav a.active{font-weight:bold;color:#fff}"
    "nav .title{font-size:16px;font-weight:bold;color:#8cf;margin-right:auto}"
    "#messages{flex:1;overflow-y:auto;padding:16px;display:flex;flex-direction:column;gap:12px}"
    ".msg{max-width:80%;padding:10px 14px;border-radius:10px;font-size:14px;"
    "line-height:1.5;white-space:pre-wrap;word-wrap:break-word}"
    ".msg.user{align-self:flex-end;background:#1a3a5c;color:#cdf;border-bottom-right-radius:2px}"
    ".msg.assistant{align-self:flex-start;background:#1a1a2e;color:#eee;"
    "border-bottom-left-radius:2px}"
    ".msg.assistant pre{background:#0a0a1a;padding:8px 10px;border-radius:4px;"
    "overflow-x:auto;margin:6px 0;font-size:13px}"
    ".msg.assistant code{background:#0a0a1a;padding:1px 4px;border-radius:3px;font-size:13px}"
    ".tool{margin:4px 0;padding:8px 10px;background:#0d1117;border-left:3px solid #456;"
    "border-radius:4px;font-size:12px;color:#888}"
    ".tool summary{cursor:pointer;color:#8cf;font-size:12px}"
    ".tool pre{margin-top:6px;font-size:11px;color:#aaa;max-height:200px;overflow-y:auto;"
    "white-space:pre-wrap}"
    "#input-area{padding:12px 16px;background:#1a1a2e;border-top:1px solid #333;"
    "display:flex;gap:8px}"
    "#input-area textarea{flex:1;padding:10px;background:#111;color:#eee;border:1px solid #444;"
    "border-radius:6px;font-size:14px;resize:none;font-family:system-ui;min-height:44px;"
    "max-height:200px}"
    "#input-area textarea:focus{outline:none;border-color:#8cf}"
    "#input-area button{padding:10px 20px;background:#234;color:#8cf;border:1px solid #456;"
    "border-radius:6px;cursor:pointer;font-size:14px;white-space:nowrap}"
    "#input-area button:hover{background:#345}"
    "#input-area button:disabled{opacity:0.5;cursor:not-allowed}"
    ".typing{color:#666;font-style:italic;font-size:13px;padding:4px 14px}"
    ".working{display:flex;align-items:center;gap:8px;padding:8px 14px;color:#8cf;"
    "font-size:13px}"
    ".working .dots{display:inline-flex;gap:4px}"
    ".working .dots span{width:6px;height:6px;border-radius:50%;background:#8cf;"
    "animation:pulse 1.4s infinite ease-in-out}"
    ".working .dots span:nth-child(2){animation-delay:0.2s}"
    ".working .dots span:nth-child(3){animation-delay:0.4s}"
    "@keyframes pulse{0%,80%,100%{opacity:0.2;transform:scale(0.8)}"
    "40%{opacity:1;transform:scale(1)}}"
    "#tab-bar{display:flex;background:#151525;border-bottom:1px solid #333;padding:0 8px;"
    "align-items:stretch;gap:0;overflow-x:auto;flex-shrink:0}"
    ".tab{padding:8px 16px;font-size:13px;color:#888;cursor:pointer;border:none;"
    "background:transparent;display:flex;align-items:center;gap:6px;white-space:nowrap;"
    "border-bottom:2px solid transparent;min-width:0}"
    ".tab:hover{color:#ccc;background:#1a1a2e}"
    ".tab.active{color:#8cf;border-bottom-color:#8cf;background:#1a1a2e}"
    ".tab .close{font-size:11px;color:#666;cursor:pointer;padding:2px 4px;border-radius:3px}"
    ".tab .close:hover{color:#f88;background:#333}"
    ".tab-title{max-width:120px;overflow:hidden;text-overflow:ellipsis}"
    "#new-tab{padding:8px 12px;font-size:16px;color:#666;cursor:pointer;border:none;"
    "background:transparent;line-height:1}"
    "#new-tab:hover{color:#8cf}"
    "</style></head><body>"
    "<nav>"
    "<span class='title'>aimee</span>"
    "<a href='/chat' class='active'>Chat</a>"
    "<a href='/dashboard'>Dashboard</a>"
    "<a href='/logout'>Logout</a>"
    "</nav>"
    "<div id='tab-bar'>"
    "<button id='new-tab' onclick='newTab()' title='New tab'>+</button>"
    "</div>"
    "<div id='messages'></div>"
    "<div id='input-area'>"
    "<textarea id='input' placeholder='Type a message... (Shift+Enter for newline)'"
    " rows='1'></textarea>"
    "<button id='send' onclick='sendMessage()'>Send</button>"
    "</div>"
    "<script>"
    "const msgs=document.getElementById('messages');"
    "const input=document.getElementById('input');"
    "const sendBtn=document.getElementById('send');"
    "let sending=false;"
    ""
    /* --- Tab management --- */
    "let tabs=[];"
    "let activeIdx=0;"
    ""
    "function saveTabs(){"
    "localStorage.setItem('aimee_chat_tabs',JSON.stringify(tabs));}"
    ""
    "function loadTabs(){"
    "try{tabs=JSON.parse(localStorage.getItem('aimee_chat_tabs')||'[]');"
    "}catch(e){tabs=[];}"
    "if(!tabs.length)tabs=[{title:'Chat',messages:[],sid:''}];"
    "activeIdx=Math.min(activeIdx,tabs.length-1);"
    "renderTabs();renderMessages();}"
    ""
    "function renderTabs(){"
    "const bar=document.getElementById('tab-bar');"
    "const btn=document.getElementById('new-tab');"
    "bar.querySelectorAll('.tab').forEach(function(t){t.remove();});"
    "tabs.forEach(function(t,i){"
    "const el=document.createElement('div');"
    "el.className='tab'+(i===activeIdx?' active':'');"
    "el.innerHTML='<span class=\"tab-title\">'+escHtml(t.title)+'</span>'"
    "+(tabs.length>1?'<span class=\"close\" "
    "onclick=\"event.stopPropagation();closeTab('+i+')\">x</span>':'');"
    "el.onclick=function(){switchTab(i);};"
    "bar.insertBefore(el,btn);});}"
    ""
    "function switchTab(i){"
    "if(i===activeIdx)return;"
    "saveCurrentTab();"
    "activeIdx=i;"
    "renderTabs();renderMessages();}"
    ""
    "function newTab(){"
    "saveCurrentTab();"
    "tabs.push({title:'Chat '+(tabs.length+1),messages:[],sid:''});"
    "activeIdx=tabs.length-1;"
    "saveTabs();renderTabs();renderMessages();input.focus();}"
    ""
    "function closeTab(i){"
    "if(tabs.length<=1)return;"
    "tabs.splice(i,1);"
    "if(activeIdx>=tabs.length)activeIdx=tabs.length-1;"
    "saveTabs();renderTabs();renderMessages();}"
    ""
    "function saveCurrentTab(){"
    "if(!tabs[activeIdx])return;"
    "let items=[];"
    "msgs.querySelectorAll('.msg').forEach(function(el){"
    "items.push({role:el.classList.contains('user')?'user':'assistant',"
    "text:el.getAttribute('data-raw')||''});});"
    "tabs[activeIdx].messages=items;"
    "saveTabs();}"
    ""
    "function renderMessages(){"
    "msgs.innerHTML='';"
    "if(!tabs[activeIdx])return;"
    "tabs[activeIdx].messages.forEach(function(m){"
    "if(!m.text)return;"
    "addMsg(m.role,m.text);});"
    "if(tabs[activeIdx].messages.length)msgs.scrollTop=msgs.scrollHeight;}"
    ""
    "function saveHistory(){saveCurrentTab();}"
    ""
    /* --- Init --- */
    "async function initSession(){"
    "try{"
    "let r=await fetch('/api/chat/session');"
    "let s=await r.json();"
    "if(s.csrf)window._csrf=s.csrf;"
    "}catch(e){}}"
    "initSession();"
    "loadTabs();"
    ""
    "input.addEventListener('keydown',function(e){"
    "if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage();}});"
    ""
    "input.addEventListener('input',function(){"
    "this.style.height='auto';"
    "this.style.height=Math.min(this.scrollHeight,200)+'px';});"
    ""
    "function escHtml(s){"
    "return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}"
    ""
    "function renderMd(text){"
    "let h=escHtml(text);"
    "h=h.replace(/```([\\s\\S]*?)```/g,function(m,c){return '<pre>'+c+'</pre>';});"
    "h=h.replace(/`([^`]+)`/g,'<code>$1</code>');"
    "h=h.replace(/\\*\\*([^*]+)\\*\\*/g,'<strong>$1</strong>');"
    "return h;}"
    ""
    "function addMsg(role,content){"
    "const d=document.createElement('div');"
    "d.className='msg '+role;"
    "d.setAttribute('data-raw',content);"
    "d.innerHTML=renderMd(content);"
    "msgs.appendChild(d);"
    "msgs.scrollTop=msgs.scrollHeight;"
    "return d;}"
    ""
    "function addTool(name,args,result){"
    "const d=document.createElement('details');"
    "d.className='tool';"
    "d.innerHTML='<summary>Tool: '+escHtml(name)+'</summary>'+"
    "'<pre>'+escHtml(args)+'</pre>'+"
    "(result?'<pre>'+escHtml(result)+'</pre>':'');"
    "msgs.appendChild(d);"
    "msgs.scrollTop=msgs.scrollHeight;"
    "return d;}"
    ""
    "async function sendMessage(){"
    "if(sending)return;"
    "const text=input.value.trim();"
    "if(!text)return;"
    "input.value='';"
    "input.style.height='auto';"
    "sending=true;"
    "sendBtn.disabled=true;"
    ""
    /* Auto-title from first message */
    "if(tabs[activeIdx]&&tabs[activeIdx].messages.length===0){"
    "tabs[activeIdx].title=text.substring(0,30)+(text.length>30?'...':'');"
    "renderTabs();}"
    ""
    "addMsg('user',text);"
    "saveHistory();"
    ""
    "function showWorking(){"
    "let w=document.querySelector('.working');"
    "if(!w){w=document.createElement('div');"
    "w.className='working';"
    "w.innerHTML='<div class=\"dots\"><span></span><span></span><span></span></div> Working';"
    "msgs.appendChild(w);msgs.scrollTop=msgs.scrollHeight;}"
    "return w;}"
    "function hideWorking(){"
    "let w=document.querySelector('.working');if(w)w.remove();}"
    ""
    "showWorking();"
    "let assistDiv=null;"
    "let fullText='';"
    ""
    "try{"
    "const resp=await fetch('/api/chat/send',{"
    "method:'POST',"
    "headers:{'Content-Type':'application/json','X-CSRF-Token':window._csrf||''},"
    "body:JSON.stringify({message:text,"
    "claude_session_id:(tabs[activeIdx]&&tabs[activeIdx].sid)||''})});"
    ""
    "if(resp.status===401){window.location='/login';return;}"
    ""
    "const reader=resp.body.getReader();"
    "const decoder=new TextDecoder();"
    "let buf='';"
    ""
    "while(true){"
    "const{done,value}=await reader.read();"
    "if(done)break;"
    "buf+=decoder.decode(value,{stream:true});"
    ""
    "let lines=buf.split('\\n');"
    "buf=lines.pop();"
    ""
    "let evtType=null;"
    "for(let line of lines){"
    "if(line.startsWith('event: ')){evtType=line.slice(7).trim();}"
    "else if(line.startsWith('data: ')&&evtType){"
    "try{"
    "const data=JSON.parse(line.slice(6));"
    "if(evtType==='turn_start'){"
    "hideWorking();"
    "assistDiv=addMsg('assistant','');"
    "fullText='';}"
    "else if(evtType==='text'){"
    "if(!assistDiv){hideWorking();assistDiv=addMsg('assistant','');fullText='';}"
    "fullText+=data.content||'';"
    "assistDiv.setAttribute('data-raw',fullText);"
    "assistDiv.innerHTML=renderMd(fullText);"
    "msgs.scrollTop=msgs.scrollHeight;}"
    "else if(evtType==='turn_end'){"
    "saveHistory();"
    "assistDiv=null;"
    "showWorking();}"
    "else if(evtType==='error'){"
    "hideWorking();"
    "if(!assistDiv){assistDiv=addMsg('assistant','');fullText='';}"
    "fullText+='\\n\\n**Error:** '+(data.message||'Unknown error');"
    "assistDiv.setAttribute('data-raw',fullText);"
    "assistDiv.innerHTML=renderMd(fullText);}"
    "else if(evtType==='session'){"
    "if(tabs[activeIdx])tabs[activeIdx].sid=data.id||'';"
    "saveTabs();}"
    "else if(evtType==='done'){"
    "hideWorking();"
    "saveHistory();}"
    "}catch(e){}"
    "evtType=null;}}"
    "}"
    "}catch(e){"
    "hideWorking();"
    "if(!assistDiv){assistDiv=addMsg('assistant','');fullText='';}"
    "fullText+='\\n\\n**Connection error:** '+e.message;"
    "assistDiv.setAttribute('data-raw',fullText);"
    "assistDiv.innerHTML=renderMd(fullText);"
    "saveHistory();}"
    "finally{"
    "sending=false;"
    "sendBtn.disabled=false;"
    "input.focus();}}"
    ""
    "document.getElementById('input').focus();"
    "document.querySelectorAll('a[href=\"/logout\"]').forEach(function(a){"
    "a.addEventListener('click',function(){"
    "localStorage.removeItem('aimee_chat_tabs');});});"
    "</script></body></html>";

const char *dashboard_page_html =
    "<!DOCTYPE html><html><head><meta charset='utf-8'>"
    "<title>aimee - dashboard</title>"
    "<style>"
    "*{box-sizing:border-box;margin:0;padding:0}"
    "body{font-family:system-ui;background:#111;color:#eee;height:100vh;display:flex;"
    "flex-direction:column;overflow:hidden}"
    "nav{background:#1a1a2e;padding:10px 20px;display:flex;align-items:center;gap:16px;"
    "border-bottom:1px solid #333;flex-shrink:0}"
    "nav a{color:#8cf;text-decoration:none;font-size:14px}"
    "nav a:hover{text-decoration:underline}"
    "nav a.active{font-weight:bold;color:#fff}"
    "nav .title{font-size:16px;font-weight:bold;color:#8cf;margin-right:auto}"
    ".dashboard{flex:1;display:grid;"
    "grid-template-columns:1fr 1fr 1fr;grid-template-rows:1fr 1fr;gap:0;overflow:hidden}"
    ".win{display:flex;flex-direction:column;border:1px solid #333;overflow:hidden;"
    "min-height:0}"
    ".win-head{background:#1a1a2e;padding:6px 12px;font-size:13px;font-weight:bold;"
    "color:#adf;border-bottom:1px solid #333;display:flex;align-items:center;"
    "flex-shrink:0;gap:8px}"
    ".win-head .tag{font-size:10px;color:#888;font-weight:normal}"
    ".win-body{flex:1;overflow-y:auto;padding:8px;font-size:12px}"
    "table{width:100%;border-collapse:collapse}"
    "th{text-align:left;padding:4px 6px;border-bottom:1px solid #444;color:#888;"
    "font-size:11px;position:sticky;top:0;background:#111}"
    "td{padding:4px 6px;border-bottom:1px solid #1a1a1a}"
    ".badge{display:inline-block;padding:1px 6px;border-radius:3px;font-size:10px}"
    ".badge.success{background:#143;color:#4f4}"
    ".badge.error{background:#411;color:#f44}"
    ".badge.running{background:#431;color:#fa0}"
    ".num{text-align:right;font-variant-numeric:tabular-nums}"
    ".log-agent{color:#8cf}.log-decision{color:#fa0}"
    ".log-detail{color:#888;max-width:300px;overflow:hidden;text-overflow:ellipsis;"
    "white-space:nowrap}"
    "#refresh{padding:4px 10px;background:#234;color:#8cf;border:1px solid #456;"
    "border-radius:3px;cursor:pointer;font-size:11px}"
    "</style></head><body>"
    "<nav>"
    "<span class='title'>aimee</span>"
    "<a href='/chat'>Chat</a>"
    "<a href='/dashboard' class='active'>Dashboard</a>"
    "<a href='/logout'>Logout</a>"
    "<button id='refresh' onclick='load()'>Refresh</button>"
    "</nav>"
    "<div class='dashboard'>"
    "<div class='win'><div class='win-head'>Delegations<span class='tag' "
    "id='del-count'></span></div>"
    "<div class='win-body' id='delegations'></div></div>"
    "<div class='win'><div class='win-head'>Metrics</div>"
    "<div class='win-body' id='metrics'></div></div>"
    "<div class='win'><div class='win-head'>Execution Plans</div>"
    "<div class='win-body' id='plans'></div></div>"
    "<div class='win'><div class='win-head'>Traces</div>"
    "<div class='win-body' id='traces'></div></div>"
    "<div class='win'><div class='win-head'>Memory</div>"
    "<div class='win-body' id='memory'></div></div>"
    "<div class='win'><div class='win-head'>Logs<span class='tag' id='log-count'></span></div>"
    "<div class='win-body' id='logs'></div></div>"
    "</div>"
    "<script>"
    "function e(s){if(s==null)return'';return String(s).replace(/&/g,'&amp;')"
    ".replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\\\"/g,'&quot;')}"
    "async function load(){"
    "try{"
    "let[d,m,t,s,p,l]=await Promise.all(["
    "fetch('/api/delegations').then(r=>r.json()),"
    "fetch('/api/metrics').then(r=>r.json()),"
    "fetch('/api/traces').then(r=>r.json()),"
    "fetch('/api/memory-stats').then(r=>r.json()),"
    "fetch('/api/plans').then(r=>r.json()),"
    "fetch('/api/logs').then(r=>r.json())]);"
    "document.getElementById('del-count').textContent='('+d.length+')';"
    "document.getElementById('delegations').innerHTML='<table><tr><th>Agent</th><th>Role</th>"
    "<th>Status</th><th>Turns</th><th>Tools</th><th>Latency</th></tr>'"
    "+d.map(r=>'<tr><td>'+e(r.agent)+'</td><td>'+e(r.role)+'</td><td><span class=\"badge '+"
    "(r.success?'success':'error')+'\">'"
    "+(r.success?'OK':'ERR')+'</span></td><td class=\"num\">'+r.turns+'</td>"
    "<td class=\"num\">'+r.tool_calls+'</td>"
    "<td class=\"num\">'+r.latency_ms+'ms</td></tr>').join('')+'</table>';"
    "document.getElementById('metrics').innerHTML='<table><tr><th>Role</th><th>Total</th>"
    "<th>OK</th><th>Avg Lat</th><th>Tokens</th></tr>'"
    "+m.map(r=>'<tr><td>'+e(r.role)+'</td><td class=\"num\">'+r.total+'</td>"
    "<td class=\"num\">'+r.successes+'</td><td class=\"num\">'+r.avg_latency_ms+'ms</td>"
    "<td class=\"num\">'+r.tokens+'</td></tr>').join('')+'</table>';"
    "document.getElementById('traces').innerHTML='<table><tr><th>Turn</th><th>Tool</th>"
    "<th>Dir</th></tr>'"
    "+t.map(r=>'<tr><td class=\"num\">'+r.turn+'</td><td>'"
    "+e(r.tool_name||'--')+'</td><td>'+e(r.direction)+'</td></tr>').join('')+'</table>';"
    "document.getElementById('memory').innerHTML='<table><tr><th>Tier</th><th>Kind</th>"
    "<th>Count</th></tr>'"
    "+s.map(r=>'<tr><td>'+e(r.tier)+'</td><td>'+e(r.kind)+'</td>"
    "<td class=\"num\">'+r.count+'</td></tr>').join('')+'</table>';"
    "document.getElementById('plans').innerHTML='<table><tr><th>ID</th><th>Agent</th>"
    "<th>Status</th><th>Steps</th><th>Task</th></tr>'"
    "+p.map(r=>'<tr><td class=\"num\">'+r.id+'</td><td>'+e(r.agent)+'</td>"
    "<td><span class=\"badge "
    "'+(r.status==\"done\"?'success':r.status==\"failed\"?'error':'running')"
    "+'\">'+e(r.status)+'</span></td><td class=\"num\">'+r.done_steps+'/'+r.total_steps+'</td>"
    "<td>'+e(r.task.substring(0,60))+'</td></tr>').join('')+'</table>';"
    "document.getElementById('log-count').textContent='('+l.length+')';"
    "document.getElementById('logs').innerHTML='<table><tr><th>Time</th><th>Source</th>"
    "<th>Who</th><th>What</th><th>Detail</th></tr>'"
    "+l.map(r=>'<tr><td>'+e(r.timestamp)+'</td>"
    "<td><span class=\"'+(r.source==='agent'?'log-agent':'log-decision')+'\">"
    "'+e(r.source)+'</span></td>"
    "<td>'+e(r.who)+'</td><td>'+e(r.what)+'</td>"
    "<td class=\"log-detail\" title=\"'+e(r.detail)+'\">'+e(r.detail)+'</td></tr>').join('')"
    "+'</table>';"
    "}catch(err){console.error('load failed',err);}}"
    "load();setInterval(load,15000);"
    "</script></body></html>";
